export const ACTIONS = {
    LOGIN : "LOGIN",
    LOGOUT : "LOGOUT",
    CHECK_AUTH : "CHECK_AUTH",
    SET_USER : "SET_USER",
    SET_MYEXAMS : "SET_MYEXAMS",
    START_EXAM : "START_EXAM",
    SUBMIT_EXAM : "SUBMIT_EXAM",
    SET_SCORE : "SET_SCORE",
    SEE_SCORE : "SEE_SCORE",

    SET_STUDENTS : "SET_STUDENTS",
    LIST_OF_STUDENTS : "LIST_OF_STUDENTS",
    NEW_SESSION : "NEW_SESSION",
    SET_SESSION_LIST : "SET_SESSION_LIST",
    LIST_OF_SESSION : "LIST_OF_SESSION",  

    SET_LEADERBOARD : "SET_LEADERBOARD",
    LIST_LEADERBOARD : "LIST_LEADERBOARD",
    GET_SCORE : "GET_SCORE"
}